# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15yEJb9nTv8rkIhNWt8d-E3s7BLiYqYuo
"""

from google.colab import drive
drive.mount('/content/drive')

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing import image
#from tensorflow.keras.optimizers import RMSprop
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
import cv2
import os

import pathlib

img = pathlib.Path('/content/drive/MyDrive/CNN/img')

cv2.imread("/content/drive/MyDrive/CNN/img/train/car/car20.jpg").shape
#print(cv2.imread("/content/drive/MyDrive/CNN/img/train/car/Copie de car8.jpg"))
img1=cv2.imread("/content/drive/MyDrive/CNN/img/train/car/car20.jpg")

plt.imshow(img1)

#Convert to bw
img_bw = cv2.cvtColor(img1, cv2.COLOR_RGB2GRAY)
#img_bw = cv2.imdecode(img1, cv2.IMREAD_GRAYSCALE)
(thresh, img_bw) = cv2.threshold(img_bw, 127, 255, cv2.THRESH_BINARY)
plt.axis('off')
plt.imshow(cv2.cvtColor(img_bw, cv2.COLOR_BGR2RGB))

kernel = np.matrix([[-1,-1,-1],[1,1,1],[0,0,0]])
print(kernel)
img_1 = cv2.filter2D(img_bw, -1, kernel)
plt.axis('off')
plt.imshow(cv2.cvtColor(img_1, cv2.COLOR_BGR2RGB))

kernel = np.matrix([[0,0,0],[1,1,1],[-1,-1,-1]])
print(kernel)
img_1 = cv2.filter2D(img_bw, -1, kernel)
plt.axis('off')
plt.imshow(cv2.cvtColor(img_1, cv2.COLOR_BGR2RGB))

kernel = np.matrix([[-1,1,0],[-1,1,0],[-1,1,0]])
print(kernel)
img_1 = cv2.filter2D(img_bw, -1, kernel)
plt.axis('off')
plt.imshow(cv2.cvtColor(img_1, cv2.COLOR_BGR2RGB))

train = ImageDataGenerator(rescale= 1/255)
validation =ImageDataGenerator(rescale= 1/255)

train_dataset = train.flow_from_directory('/content/drive/MyDrive/CNN/img/train',
                                          target_size= (200,200),
                                          batch_size = 3,
                                          class_mode = 'binary')

validation_dataset = validation.flow_from_directory('/content/drive/MyDrive/CNN/img/val',
                                          target_size= (200,200),
                                          batch_size = 3,
                                          class_mode = 'binary')

train_dataset.class_indices
#train_dataset.classes

"""Sequential model= will connect together a list of layers in order"""

model = tf.keras.models.Sequential([tf.keras.layers.Conv2D(16,(3,3),activation = 'relu' ,input_shape =(200,200,3)), # give the input dimensions in the first layer [height, width, color channels(RGB)]
                                     tf.keras.layers.MaxPool2D(2,2),
                                      #
                                     tf.keras.layers.Conv2D(32,(3,3),activation = 'relu'),
                                     tf.keras.layers.MaxPool2D(2,2),
                                      
                                     tf.keras.layers.Conv2D(64,(3,3),activation = 'relu'),
                                     tf.keras.layers.MaxPool2D(2,2),
                                      ##
                                     tf.keras.layers.Flatten(),
                                     tf.keras.layers.Dense(512,activation= 'relu'),
                                      ##
                                     tf.keras.layers.Dense(1,activation='sigmoid')
                                     ])

model.compile(loss= "binary_crossentropy",
              optimizer ='adam',
              metrics =['binary_accuracy'])

model_fit = model.fit(train_dataset,
                      steps_per_epoch = 3,
                      epochs= 10,
                      validation_data= validation_dataset)

model.summary()

dir_path = '/content/drive/MyDrive/CNN/img/test'
print(os.listdir(dir_path))
for i in os.listdir(dir_path):
     img = image.load_img(dir_path+'/'+ i, target_size=(200,200))
     plt. imshow(img)
     plt.show()
     x=image.img_to_array(img)
     X = np.expand_dims(x,axis =0)
     images = np.vstack([X])
     val = model.predict(images)
     if val == 0:
         print("car")
     else:
         print("tree")

import pandas as pd

# convert the training history to a dataframe
history_df = pd.DataFrame(model_fit.history)
# use Pandas native plot method
history_df['loss'].plot();

'''history_df = pd.DataFrame(history.history)
history_df.loc[:, ['loss', 'val_loss']].plot();
print("Minimum validation loss: {}".format(history_df['val_loss'].min()))'''

